### ISSUE TITLE
Truncated password containing commas

### ISSUE THREAD

**Issue by ethiquable** [infamousjoeg/pyaim#55]
**Describe the bug**
The password string is truncated when it contains commas

**To Reproduce**
1. Change the password to contain a comma on Cyberark
2. Use pyaim to retrieve the password
3. Check response['Password'], it is truncated up to the comma

**Expected behavior**
I would like to get the password even if it contains commas

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Red Hat 8
 - python 3.9.5
 - pyaim 1.2.9

**Smartphone (please complete the following information):**

**Additional context**

**Comment by diaznet** [comment]
I believe this is because by default commas are used to separate values returned by Password SDK. I think they need to implement the handling of /d / -d parameter that lets you specify the delimiter for separating the output fields.

I have patched the code in my implementation of pyaim to handle this separator specification but apparently we cannot contribute it back according to the [README.md](https://github.com/infamousjoeg/pyaim/blob/master/README.md):

> For the time being, only internal CyberArk contributions are being considered.
